#!/usr/bin/env bash
set -u
set -o pipefail

PIC_SIMLAB_DEB="PICSimLab_0.9.2_241005_Ubuntu_24.04.1_LTS_amd64.deb"
PIC_SIMLAB_URL="https://github.com/lcgamboa/picsimlab/releases/download/v0.9.2/${PIC_SIMLAB_DEB}"
PROBE_RS_INSTALLER_URL="https://github.com/probe-rs/probe-rs/releases/latest/download/probe-rs-tools-installer.sh"
RUSTUP_INSTALLER_URL="https://sh.rustup.rs"

STATE_DIR="${EMBEDDED_RUST_SETUP_STATE_DIR:-$HOME/.local/state/embedded-rust-setup}"
DOWNLOAD_DIR="${EMBEDDED_RUST_SETUP_DOWNLOAD_DIR:-$HOME/.cache/embedded-rust-setup}"
RUN_ID="$(date +%Y%m%d-%H%M%S)"
LOG_FILE="$STATE_DIR/install-$RUN_ID.log"
ROLLBACK_FILE="$STATE_DIR/rollback-$RUN_ID.sh"

if [[ -t 1 ]]; then
  BOLD="$(printf '\033[1m')"
  DIM="$(printf '\033[2m')"
  RED="$(printf '\033[31m')"
  GREEN="$(printf '\033[32m')"
  YELLOW="$(printf '\033[33m')"
  BLUE="$(printf '\033[34m')"
  RESET="$(printf '\033[0m')"
else
  BOLD=""
  DIM=""
  RED=""
  GREEN=""
  YELLOW=""
  BLUE=""
  RESET=""
fi

APT_PACKAGES=(
  build-essential
  curl
  git
  libssl-dev
  gcc-arm-none-eabi
  binutils-arm-none-eabi
  gdb-multiarch
  qemu-system-arm
  stlink-tools
  stlink-gui
  openocd
  picocom
  minicom
  libfuse2t64
  file
  desktop-file-utils
  python3-pip
  python3-pygments
)

RUST_TARGETS=(
  thumbv6m-none-eabi
  thumbv7m-none-eabi
  thumbv7em-none-eabihf
)

CARGO_TOOLS=(
  cargo-binutils
  cargo-generate
  flip-link
  itm
)

CONNECTIVITY_SITES=(
  crates.io
  https://rust-lang.org/
  https://www.qemu.org/
  https://docs.rs/
  developer.arm.com/
  docs.nordicsemi.com
  stm32-base.org
  st.com
  github.com
  http://libopencm3.org/
)

SELECTED_APT=()
SELECTED_RUST_TARGETS=()
SELECTED_CARGO_TOOLS=()
INSTALL_RUSTUP=0
INSTALL_LLVM_TOOLS=0
INSTALL_PROBE_RS=0
INSTALL_PICSIMLAB=0

INSTALLED_APT=()
INSTALLED_RUST_TARGETS=()
INSTALLED_CARGO_TOOLS=()
INSTALLED_OTHER=()
FAILED_ITEMS=()
SKIPPED_ITEMS=()

print_header() {
  printf '\n%s%s%s\n' "$BOLD" "$1" "$RESET"
  printf '%*s\n' "${#1}" '' | tr ' ' '-'
}

log() {
  mkdir -p "$STATE_DIR" 2>/dev/null || true
  printf '[%s] %s\n' "$(date --iso-8601=seconds)" "$*" >> "$LOG_FILE"
}

prepare_runtime_dirs() {
  if ! mkdir -p "$STATE_DIR" 2>/dev/null || ! ( : > "$STATE_DIR/.write-test" ) 2>/dev/null; then
    printf '%s\n' "${YELLOW}Cannot write to $STATE_DIR; using a local log directory instead.${RESET}"
    STATE_DIR="$PWD/embedded-rust-setup-logs"
    mkdir -p "$STATE_DIR"
  else
    rm -f "$STATE_DIR/.write-test"
  fi

  if ! mkdir -p "$DOWNLOAD_DIR" 2>/dev/null || ! ( : > "$DOWNLOAD_DIR/.write-test" ) 2>/dev/null; then
    printf '%s\n' "${YELLOW}Cannot write to $DOWNLOAD_DIR; using a local download cache instead.${RESET}"
    DOWNLOAD_DIR="$PWD/embedded-rust-setup-downloads"
    mkdir -p "$DOWNLOAD_DIR"
  else
    rm -f "$DOWNLOAD_DIR/.write-test"
  fi

  LOG_FILE="$STATE_DIR/install-$RUN_ID.log"
  ROLLBACK_FILE="$STATE_DIR/rollback-$RUN_ID.sh"
}

init_rollback() {
  printf '[%s] run started\n' "$(date --iso-8601=seconds)" > "$LOG_FILE"

  {
    printf '#!/usr/bin/env bash\n'
    printf 'set -u\n'
    printf 'set -o pipefail\n\n'
    printf '# Rollback commands generated by validate_embedded_rust_setup.sh on %s.\n' "$(date --iso-8601=seconds)"
    printf '# Only items installed directly by that run are listed here.\n\n'
  } > "$ROLLBACK_FILE"
  chmod +x "$ROLLBACK_FILE"
}

append_rollback() {
  printf '%s\n' "$*" >> "$ROLLBACK_FILE"
}

status_label() {
  case "$1" in
    present) printf '%sinstalled%s' "$GREEN" "$RESET" ;;
    missing) printf '%smissing%s' "$RED" "$RESET" ;;
    selected) printf '%sselected%s' "$BLUE" "$RESET" ;;
    skipped) printf '%sskipped%s' "$YELLOW" "$RESET" ;;
    failed) printf '%sfailed%s' "$RED" "$RESET" ;;
    ok) printf '%sok%s' "$GREEN" "$RESET" ;;
    *) printf '%s' "$1" ;;
  esac
}

prompt_yes_no() {
  local prompt="$1"
  local default="${2:-n}"
  local answer suffix

  if [[ "$default" == "y" ]]; then
    suffix="[Y/n]"
  else
    suffix="[y/N]"
  fi

  while true; do
    printf '%s %s ' "$prompt" "$suffix"
    if ! read -r answer; then
      printf '\nNo input available; defaulting to no.\n'
      return 1
    fi
    answer="${answer:-$default}"
    case "$answer" in
      y|Y|yes|YES|Yes) return 0 ;;
      n|N|no|NO|No) return 1 ;;
      *) printf 'Please answer yes or no.\n' ;;
    esac
  done
}

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

source_cargo_env() {
  if [[ -f "$HOME/.cargo/env" ]]; then
    # shellcheck disable=SC1091
    . "$HOME/.cargo/env"
  fi
}

apt_installed() {
  dpkg-query -W -f='${Status}' "$1" 2>/dev/null | grep -q 'install ok installed'
}

rust_target_installed() {
  command_exists rustup && rustup target list --installed 2>/dev/null | grep -Fxq "$1"
}

rust_component_installed() {
  command_exists rustup && rustup component list --installed 2>/dev/null | grep -Eq "^$1($|[ -])"
}

cargo_tool_installed() {
  case "$1" in
    cargo-binutils) command_exists cargo-size && cargo size --version >/dev/null 2>&1 ;;
    cargo-generate) command_exists cargo-generate || cargo generate --version >/dev/null 2>&1 ;;
    flip-link) command_exists flip-link ;;
    itm) command_exists itmdump && itmdump --version >/dev/null 2>&1 ;;
    *) return 1 ;;
  esac
}

cargo_tool_check_label() {
  case "$1" in
    cargo-binutils) printf '%s' "cargo size --version" ;;
    cargo-generate) printf '%s' "cargo-generate --version" ;;
    flip-link) printf '%s' "flip-link command" ;;
    itm) printf '%s' "itmdump --version" ;;
    *) printf '%s' "command/version" ;;
  esac
}

probe_rs_installed() {
  command_exists probe-rs && probe-rs --version >/dev/null 2>&1
}

picsimlab_installed() {
  apt_installed picsimlab || command_exists PICSimLab || command_exists picsimlab || command_exists PICSimLab_NOGUI
}

picsimlab_command() {
  if command_exists picsimlab; then
    printf '%s' "picsimlab"
  elif command_exists PICSimLab; then
    printf '%s' "PICSimLab"
  elif command_exists PICSimLab_NOGUI; then
    printf '%s' "PICSimLab_NOGUI"
  else
    return 1
  fi
}

normalize_url() {
  case "$1" in
    http://*|https://*) printf '%s' "$1" ;;
    *) printf 'https://%s' "$1" ;;
  esac
}

url_host() {
  local url="$1"
  url="${url#http://}"
  url="${url#https://}"
  url="${url%%/*}"
  url="${url%%:*}"
  printf '%s' "$url"
}

url_port() {
  case "$1" in
    http://*) printf '%s' "80" ;;
    *) printf '%s' "443" ;;
  esac
}

test_tcp_reachable() {
  local url="$1"
  local host port

  host="$(url_host "$url")"
  port="$(url_port "$url")"

  if command_exists timeout; then
    timeout 5 bash -c ":</dev/tcp/$host/$port" >/dev/null 2>&1
  else
    bash -c ":</dev/tcp/$host/$port" >/dev/null 2>&1
  fi
}

test_site_reachable() {
  local input="$1"
  local url http_code

  url="$(normalize_url "$input")"

  if command_exists curl; then
    http_code="$(
      curl -L -sS -o /dev/null -w '%{http_code}' \
        --connect-timeout 5 \
        --max-time 12 \
        --compressed \
        -A 'Mozilla/5.0 embedded-rust-readiness-check' \
        "$url" 2>/dev/null || true
    )"
    if [[ "$http_code" != "000" && -n "$http_code" ]]; then
      return 0
    fi
  fi

  test_tcp_reachable "$url"
}

print_connectivity_summary() {
  local site url
  local reachable_count=0
  local failed_count=0

  print_header "Website reachability"
  printf '%-32s %-14s %s\n' "Site" "Result" "URL tested"
  printf '%-32s %-14s %s\n' "----" "------" "----------"

  for site in "${CONNECTIVITY_SITES[@]}"; do
    url="$(normalize_url "$site")"
    if test_site_reachable "$site"; then
      printf '%-32s %-23b %s\n' "$site" "$(status_label ok)" "$url"
      reachable_count=$((reachable_count + 1))
      log "site reachable: $url"
    else
      printf '%-32s %-23b %s\n' "$site" "$(status_label failed)" "$url"
      failed_count=$((failed_count + 1))
      log "site unreachable: $url"
    fi
  done

  printf '\nReachable: %s  Failed: %s\n' "$reachable_count" "$failed_count"
}

print_detection_table() {
  print_header "Readiness scan"
  printf '%-34s %-14s %s\n' "Item" "Status" "Verification"
  printf '%-34s %-14s %s\n' "----" "------" "------------"

  for package in "${APT_PACKAGES[@]}"; do
    if apt_installed "$package"; then
      printf '%-34s %-23b %s\n' "$package" "$(status_label present)" "dpkg"
    else
      printf '%-34s %-23b %s\n' "$package" "$(status_label missing)" "apt package"
    fi
  done

  if command_exists rustup; then
    printf '%-34s %-23b %s\n' "rustup" "$(status_label present)" "rustup --version"
  else
    printf '%-34s %-23b %s\n' "rustup" "$(status_label missing)" "$RUSTUP_INSTALLER_URL"
  fi

  for target in "${RUST_TARGETS[@]}"; do
    if rust_target_installed "$target"; then
      printf '%-34s %-23b %s\n' "rust target: $target" "$(status_label present)" "rustup target list"
    else
      printf '%-34s %-23b %s\n' "rust target: $target" "$(status_label missing)" "rustup target add"
    fi
  done

  if rust_component_installed llvm-tools; then
    printf '%-34s %-23b %s\n' "rust component: llvm-tools" "$(status_label present)" "rustup component list"
  else
    printf '%-34s %-23b %s\n' "rust component: llvm-tools" "$(status_label missing)" "rustup component add"
  fi

  for tool in "${CARGO_TOOLS[@]}"; do
    if cargo_tool_installed "$tool"; then
      printf '%-34s %-23b %s\n' "cargo tool: $tool" "$(status_label present)" "$(cargo_tool_check_label "$tool")"
    else
      printf '%-34s %-23b %s\n' "cargo tool: $tool" "$(status_label missing)" "cargo install"
    fi
  done

  if probe_rs_installed; then
    printf '%-34s %-23b %s\n' "probe-rs" "$(status_label present)" "probe-rs --version"
  else
    printf '%-34s %-23b %s\n' "probe-rs" "$(status_label missing)" "upstream installer"
  fi

  if picsimlab_installed; then
    printf '%-34s %-23b %s\n' "PICSimLab" "$(status_label present)" "package/command"
  else
    printf '%-34s %-23b %s\n' "PICSimLab" "$(status_label missing)" "$PIC_SIMLAB_DEB"
  fi
}

select_missing_items() {
  local package target tool

  print_header "Installation choices"
  printf '%s\n' "Answer yes for items you want this script to install now."

  for package in "${APT_PACKAGES[@]}"; do
    if ! apt_installed "$package"; then
      if prompt_yes_no "Install apt package '$package'?" "y"; then
        SELECTED_APT+=("$package")
      else
        SKIPPED_ITEMS+=("$package")
      fi
    fi
  done

  if ! command_exists rustup; then
    if prompt_yes_no "Install rustup using the official Rust installer?" "y"; then
      INSTALL_RUSTUP=1
    else
      SKIPPED_ITEMS+=("rustup")
    fi
  fi

  for target in "${RUST_TARGETS[@]}"; do
    if ! rust_target_installed "$target"; then
      if prompt_yes_no "Install Rust target '$target'?" "y"; then
        SELECTED_RUST_TARGETS+=("$target")
      else
        SKIPPED_ITEMS+=("rust target: $target")
      fi
    fi
  done

  if ! rust_component_installed llvm-tools; then
    if prompt_yes_no "Install Rust component 'llvm-tools'?" "y"; then
      INSTALL_LLVM_TOOLS=1
    else
      SKIPPED_ITEMS+=("rust component: llvm-tools")
    fi
  fi

  for tool in "${CARGO_TOOLS[@]}"; do
    if ! cargo_tool_installed "$tool"; then
      if prompt_yes_no "Install Cargo tool '$tool'?" "y"; then
        SELECTED_CARGO_TOOLS+=("$tool")
      else
        SKIPPED_ITEMS+=("cargo tool: $tool")
      fi
    fi
  done

  if ! probe_rs_installed; then
    if prompt_yes_no "Install probe-rs using the upstream installer?" "y"; then
      INSTALL_PROBE_RS=1
    else
      SKIPPED_ITEMS+=("probe-rs")
    fi
  fi

  if ! picsimlab_installed; then
    printf '%s\n' "${DIM}PICSimLab will use the pinned Ubuntu 24.04 asset: $PIC_SIMLAB_DEB${RESET}"
    if prompt_yes_no "Install PICSimLab from the pinned .deb?" "y"; then
      INSTALL_PICSIMLAB=1
    else
      SKIPPED_ITEMS+=("PICSimLab")
    fi
  fi
}

ensure_sudo() {
  if [[ "${#SELECTED_APT[@]}" -gt 0 || "$INSTALL_PICSIMLAB" -eq 1 ]]; then
    sudo -v
  fi
}

install_apt_packages() {
  local package

  if [[ "${#SELECTED_APT[@]}" -eq 0 ]]; then
    return
  fi

  print_header "Installing apt packages"
  log "apt selected: ${SELECTED_APT[*]}"

  if sudo apt update && sudo apt install -y "${SELECTED_APT[@]}"; then
    for package in "${SELECTED_APT[@]}"; do
      if apt_installed "$package"; then
        INSTALLED_APT+=("$package")
        append_rollback "sudo apt purge -y '$package'"
        log "apt installed: $package"
      else
        FAILED_ITEMS+=("$package")
        log "apt install verification failed: $package"
      fi
    done
    append_rollback "sudo apt autoremove -y"
    return
  fi

  printf '%s\n' "${YELLOW}Batch apt install failed; retrying packages individually.${RESET}"
  log "apt batch failed; retrying individually"

  for package in "${SELECTED_APT[@]}"; do
    if apt_installed "$package"; then
      continue
    fi

    if sudo apt install -y "$package" && apt_installed "$package"; then
      INSTALLED_APT+=("$package")
      append_rollback "sudo apt purge -y '$package'"
      log "apt installed after retry: $package"
    else
      FAILED_ITEMS+=("$package")
      log "apt install failed: $package"
    fi
  done
  append_rollback "sudo apt autoremove -y"
}

install_rustup_if_needed() {
  if [[ "$INSTALL_RUSTUP" -ne 1 ]]; then
    return
  fi

  print_header "Installing rustup"
  log "installing rustup"
  if curl --proto '=https' --tlsv1.2 -sSf "$RUSTUP_INSTALLER_URL" | sh -s -- -y; then
    source_cargo_env
    if command_exists rustup; then
      INSTALLED_OTHER+=("rustup")
      append_rollback "rustup self uninstall -y"
      log "rustup installed"
    else
      FAILED_ITEMS+=("rustup")
      log "rustup installer completed but rustup was not found"
    fi
  else
    FAILED_ITEMS+=("rustup")
    log "rustup installer failed"
  fi
}

install_rust_items() {
  local target tool

  source_cargo_env

  if [[ "${#SELECTED_RUST_TARGETS[@]}" -gt 0 || "$INSTALL_LLVM_TOOLS" -eq 1 ]]; then
    if ! command_exists rustup; then
      printf '%s\n' "${RED}rustup is unavailable; skipping Rust targets/components.${RESET}"
      for target in "${SELECTED_RUST_TARGETS[@]}"; do
        FAILED_ITEMS+=("rust target: $target")
      done
      [[ "$INSTALL_LLVM_TOOLS" -eq 1 ]] && FAILED_ITEMS+=("rust component: llvm-tools")
    fi
  fi

  if command_exists rustup; then
    for target in "${SELECTED_RUST_TARGETS[@]}"; do
      print_header "Installing Rust target $target"
      if rustup target add "$target" && rust_target_installed "$target"; then
        INSTALLED_RUST_TARGETS+=("$target")
        append_rollback "rustup target remove '$target'"
        log "rust target installed: $target"
      else
        FAILED_ITEMS+=("rust target: $target")
        log "rust target install failed: $target"
      fi
    done

    if [[ "$INSTALL_LLVM_TOOLS" -eq 1 ]]; then
      print_header "Installing Rust component llvm-tools"
      if rustup component add llvm-tools && rust_component_installed llvm-tools; then
        INSTALLED_OTHER+=("rust component: llvm-tools")
        append_rollback "rustup component remove llvm-tools"
        log "rust component installed: llvm-tools"
      else
        FAILED_ITEMS+=("rust component: llvm-tools")
        log "rust component install failed: llvm-tools"
      fi
    fi
  fi

  if [[ "${#SELECTED_CARGO_TOOLS[@]}" -gt 0 ]]; then
    if ! command_exists cargo; then
      printf '%s\n' "${RED}cargo is unavailable; skipping Cargo tools.${RESET}"
      for tool in "${SELECTED_CARGO_TOOLS[@]}"; do
        FAILED_ITEMS+=("cargo tool: $tool")
      done
      return
    fi

    for tool in "${SELECTED_CARGO_TOOLS[@]}"; do
      print_header "Installing Cargo tool $tool"
      if cargo install "$tool" && cargo_tool_installed "$tool"; then
        INSTALLED_CARGO_TOOLS+=("$tool")
        append_rollback "cargo uninstall '$tool'"
        log "cargo tool installed: $tool"
      else
        FAILED_ITEMS+=("cargo tool: $tool")
        log "cargo tool install failed: $tool"
      fi
    done
  fi
}

install_probe_rs() {
  if [[ "$INSTALL_PROBE_RS" -ne 1 ]]; then
    return
  fi

  print_header "Installing probe-rs"
  log "installing probe-rs"
  if curl --proto '=https' --tlsv1.2 -LsSf "$PROBE_RS_INSTALLER_URL" | sh; then
    source_cargo_env
    if probe_rs_installed; then
      INSTALLED_OTHER+=("probe-rs")
      append_rollback "rm -f '$HOME/.cargo/bin/probe-rs' '$HOME/.cargo/bin/cargo-embed' '$HOME/.cargo/bin/cargo-flash'"
      log "probe-rs installed"
    else
      FAILED_ITEMS+=("probe-rs")
      log "probe-rs installer completed but probe-rs was not found"
    fi
  else
    FAILED_ITEMS+=("probe-rs")
    log "probe-rs installer failed"
  fi
}

install_picsimlab() {
  if [[ "$INSTALL_PICSIMLAB" -ne 1 ]]; then
    return
  fi

  print_header "Installing PICSimLab"
  mkdir -p "$DOWNLOAD_DIR"
  log "installing PICSimLab from $PIC_SIMLAB_URL"

  if [[ "$(uname -m)" != "x86_64" ]]; then
    printf '%s\n' "${RED}PICSimLab pinned .deb is amd64 only; skipping on $(uname -m).${RESET}"
    FAILED_ITEMS+=("PICSimLab")
    log "PICSimLab skipped because architecture is not x86_64"
    return
  fi

  if [[ -r /etc/os-release ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    if [[ "${ID:-}" != "ubuntu" ]]; then
      printf '%s\n' "${RED}PICSimLab install is configured for Ubuntu only; skipping.${RESET}"
      FAILED_ITEMS+=("PICSimLab")
      log "PICSimLab skipped because OS ID is ${ID:-unknown}"
      return
    fi

    if [[ "${VERSION_ID:-}" != "24.04" ]]; then
      printf '%s\n' "${YELLOW}This is Ubuntu ${VERSION_ID:-unknown}; the pinned PICSimLab package is built for Ubuntu 24.04.1.${RESET}"
      if ! prompt_yes_no "Continue with the pinned PICSimLab .deb anyway?" "n"; then
        SKIPPED_ITEMS+=("PICSimLab")
        log "PICSimLab skipped by user because Ubuntu version is ${VERSION_ID:-unknown}"
        return
      fi
    fi
  fi

  if ! curl -L --fail --output "$DOWNLOAD_DIR/$PIC_SIMLAB_DEB" "$PIC_SIMLAB_URL"; then
    FAILED_ITEMS+=("PICSimLab download")
    log "PICSimLab download failed"
    return
  fi

  if sudo dpkg -i "$DOWNLOAD_DIR/$PIC_SIMLAB_DEB"; then
    :
  else
    printf '%s\n' "${YELLOW}dpkg reported missing dependencies; running apt --fix-broken install.${RESET}"
    sudo apt --fix-broken install -y
  fi

  if picsimlab_installed; then
    INSTALLED_OTHER+=("PICSimLab")
    append_rollback "sudo apt purge -y picsimlab"
    append_rollback "sudo apt autoremove -y"
    log "PICSimLab installed"
  else
    FAILED_ITEMS+=("PICSimLab")
    log "PICSimLab install verification failed"
  fi
}

verify_final_state() {
  print_header "Final verification"
  printf '%-34s %-14s %s\n' "Item" "Result" "Check"
  printf '%-34s %-14s %s\n' "----" "------" "-----"

  verify_line "build-essential" "dpkg" apt_installed build-essential
  verify_line "curl" "curl --version" command_exists curl
  verify_line "git" "git --version" command_exists git
  verify_line "libssl-dev" "dpkg" apt_installed libssl-dev
  verify_line "rustup" "rustup --version" command_exists rustup

  for target in "${RUST_TARGETS[@]}"; do
    verify_line "rust target: $target" "rustup target list" rust_target_installed "$target"
  done

  verify_line "llvm-tools" "rustup component list" rust_component_installed llvm-tools
  verify_line "cargo-binutils" "cargo size --version" cargo_tool_installed cargo-binutils
  verify_line "cargo-generate" "cargo-generate --version" cargo_tool_installed cargo-generate
  verify_line "flip-link" "flip-link --version" cargo_tool_installed flip-link
  verify_line "itm" "itmdump --version" cargo_tool_installed itm
  verify_line "gcc-arm-none-eabi" "dpkg" apt_installed gcc-arm-none-eabi
  verify_line "binutils-arm-none-eabi" "dpkg" apt_installed binutils-arm-none-eabi
  verify_line "gdb-multiarch" "dpkg" apt_installed gdb-multiarch
  verify_line "qemu-system-arm" "dpkg" apt_installed qemu-system-arm
  verify_line "stlink-tools" "dpkg" apt_installed stlink-tools
  verify_line "stlink-gui" "dpkg" apt_installed stlink-gui
  verify_line "openocd" "dpkg" apt_installed openocd
  verify_line "probe-rs" "probe-rs --version" probe_rs_installed
  verify_line "picocom" "dpkg" apt_installed picocom
  verify_line "minicom" "dpkg" apt_installed minicom
  verify_line "PICSimLab deps: libfuse2t64" "dpkg" apt_installed libfuse2t64
  verify_line "PICSimLab" "package/command" picsimlab_installed
  verify_line "python3-pip" "dpkg" apt_installed python3-pip
  verify_line "python3-pygments" "dpkg" apt_installed python3-pygments
}

verify_line() {
  local name="$1"
  local check="$2"
  local fn="$3"
  shift 3

  if "$fn" "$@"; then
    printf '%-34s %-23b %s\n' "$name" "$(status_label ok)" "$check"
  else
    printf '%-34s %-23b %s\n' "$name" "$(status_label failed)" "$check"
  fi
}

run_blinky_picsimlab_test() {
  local project_parent project_dir elf_file bin_file sim_cmd

  print_header "Rust and PICSimLab test"

  if ! prompt_yes_no "Create, build, and load a no_std Blue Pill blinky test in PICSimLab?" "n"; then
    log "Rust/PICSimLab integration test skipped by user"
    return
  fi

  source_cargo_env

  if ! command_exists cargo; then
    printf '%s\n' "${RED}cargo is not available; cannot build the test project.${RESET}"
    FAILED_ITEMS+=("Rust/PICSimLab test: cargo")
    log "Rust/PICSimLab test failed: cargo missing"
    return
  fi

  if ! rust_target_installed thumbv7m-none-eabi; then
    printf '%s\n' "${RED}Rust target thumbv7m-none-eabi is missing; cannot build for STM32F103.${RESET}"
    FAILED_ITEMS+=("Rust/PICSimLab test: thumbv7m-none-eabi")
    log "Rust/PICSimLab test failed: target missing"
    return
  fi

  if ! command_exists arm-none-eabi-objcopy; then
    printf '%s\n' "${RED}arm-none-eabi-objcopy is missing; install binutils-arm-none-eabi first.${RESET}"
    FAILED_ITEMS+=("Rust/PICSimLab test: objcopy")
    log "Rust/PICSimLab test failed: objcopy missing"
    return
  fi

  if ! sim_cmd="$(picsimlab_command)"; then
    printf '%s\n' "${RED}PICSimLab command was not found; cannot load the binary.${RESET}"
    FAILED_ITEMS+=("Rust/PICSimLab test: PICSimLab")
    log "Rust/PICSimLab test failed: PICSimLab command missing"
    return
  fi

  project_parent="${EMBEDDED_RUST_TEST_DIR:-$PWD/embedded-rust-setup-tests}"
  project_dir="$project_parent/blinky_app"
  mkdir -p "$project_dir/src" "$project_dir/.cargo"

  printf '%s\n' "${DIM}Writing test project to $project_dir${RESET}"

  cat > "$project_dir/Cargo.toml" <<'EOF'
[package]
name = "blinky_app"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = "s"
EOF

  cat > "$project_dir/.cargo/config.toml" <<'EOF'
[build]
target = "thumbv7m-none-eabi"

[target.thumbv7m-none-eabi]
rustflags = [
  "-C", "link-arg=-Tlink.x",
]
EOF

  cat > "$project_dir/build.rs" <<'EOF'
use std::env;

fn main() {
    println!(
        "cargo:rustc-link-search={}",
        env::var("CARGO_MANIFEST_DIR").unwrap()
    );
    println!("cargo:rerun-if-changed=memory.x");
}
EOF

  cat > "$project_dir/memory.x" <<'EOF'
MEMORY
{
  FLASH : ORIGIN = 0x08000000, LENGTH = 64K
  RAM : ORIGIN = 0x20000000, LENGTH = 20K
}
EOF

  cat > "$project_dir/src/main.rs" <<'EOF'
#![no_main]
#![no_std]

use core::ptr::{read_volatile, write_volatile};
use cortex_m_rt::entry;
use panic_halt as _;

const RCC_APB2ENR: *mut u32 = 0x4002_1018 as *mut u32;
const GPIOC_CRH: *mut u32 = 0x4001_1004 as *mut u32;
const GPIOC_BSRR: *mut u32 = 0x4001_1010 as *mut u32;
const GPIOC_BRR: *mut u32 = 0x4001_1014 as *mut u32;

#[entry]
fn main() -> ! {
    unsafe {
        let rcc = read_volatile(RCC_APB2ENR);
        write_volatile(RCC_APB2ENR, rcc | (1 << 4));

        let mut crh = read_volatile(GPIOC_CRH);
        crh &= !(0b1111 << 20);
        crh |= 0b0010 << 20;
        write_volatile(GPIOC_CRH, crh);
    }

    loop {
        unsafe {
            write_volatile(GPIOC_BRR, 1 << 13);
        }
        delay();

        unsafe {
            write_volatile(GPIOC_BSRR, 1 << 13);
        }
        delay();
    }
}

#[inline(never)]
fn delay() {
    for _ in 0..8_000_000 {
        cortex_m::asm::nop();
    }
}
EOF

  print_header "Building blinky_app"
  if ! (cd "$project_dir" && cargo build --release); then
    printf '%s\n' "${RED}cargo build --release failed for the test project.${RESET}"
    FAILED_ITEMS+=("Rust/PICSimLab test: cargo build")
    log "Rust/PICSimLab test failed: cargo build"
    return
  fi

  elf_file="$project_dir/target/thumbv7m-none-eabi/release/blinky_app"
  bin_file="$project_dir/blinky_app.bin"

  print_header "Creating blinky_app.bin"
  if ! arm-none-eabi-objcopy -O binary "$elf_file" "$bin_file"; then
    printf '%s\n' "${RED}arm-none-eabi-objcopy failed.${RESET}"
    FAILED_ITEMS+=("Rust/PICSimLab test: objcopy")
    log "Rust/PICSimLab test failed: objcopy"
    return
  fi

  print_header "Launching PICSimLab"
  printf '%s\n' "${DIM}Running: $sim_cmd Blue_Pill stm32f103c8t6 $bin_file${RESET}"
  log "Rust/PICSimLab test launching: $sim_cmd Blue_Pill stm32f103c8t6 $bin_file"

  if (cd "$project_dir" && "$sim_cmd" Blue_Pill stm32f103c8t6 blinky_app.bin); then
    INSTALLED_OTHER+=("Rust/PICSimLab blinky test")
    log "Rust/PICSimLab test completed"
  else
    FAILED_ITEMS+=("Rust/PICSimLab test: launch")
    log "Rust/PICSimLab test launch failed"
  fi
}

print_run_summary() {
  local item

  print_header "Run summary"
  printf '%-34s %-14s\n' "Item" "Outcome"
  printf '%-34s %-14s\n' "----" "-------"

  for item in "${INSTALLED_APT[@]}"; do
    printf '%-34s %-23b\n' "$item" "$(status_label ok)"
  done
  for item in "${INSTALLED_RUST_TARGETS[@]}"; do
    printf '%-34s %-23b\n' "rust target: $item" "$(status_label ok)"
  done
  for item in "${INSTALLED_CARGO_TOOLS[@]}"; do
    printf '%-34s %-23b\n' "cargo tool: $item" "$(status_label ok)"
  done
  for item in "${INSTALLED_OTHER[@]}"; do
    printf '%-34s %-23b\n' "$item" "$(status_label ok)"
  done
  for item in "${SKIPPED_ITEMS[@]}"; do
    printf '%-34s %-23b\n' "$item" "$(status_label skipped)"
  done
  for item in "${FAILED_ITEMS[@]}"; do
    printf '%-34s %-23b\n' "$item" "$(status_label failed)"
  done

  printf '\nLog:      %s\n' "$LOG_FILE"
  printf 'Rollback: %s\n' "$ROLLBACK_FILE"
}

check_ubuntu() {
  if [[ ! -r /etc/os-release ]]; then
    printf '%s\n' "${RED}Cannot read /etc/os-release; this script supports Ubuntu only.${RESET}"
    exit 1
  fi

  # shellcheck disable=SC1091
  . /etc/os-release
  if [[ "${ID:-}" != "ubuntu" ]]; then
    printf '%s\n' "${RED}Unsupported OS '${ID:-unknown}'. This script supports Ubuntu only.${RESET}"
    exit 1
  fi
}

main() {
  check_ubuntu
  source_cargo_env
  prepare_runtime_dirs
  init_rollback

  printf '%s%sEmbedded Rust no_std readiness check%s\n' "$BOLD" "$BLUE" "$RESET"
  printf '%sUbuntu-only installer for the tools listed in embedded-rust-ubuntu-setup.md.%s\n' "$DIM" "$RESET"

  print_connectivity_summary
  print_detection_table
  select_missing_items
  ensure_sudo

  install_apt_packages
  install_rustup_if_needed
  install_rust_items
  install_probe_rs
  install_picsimlab

  source_cargo_env
  verify_final_state
  run_blinky_picsimlab_test
  print_run_summary
}

main "$@"
