#!/usr/bin/env bash
set -u
set -o pipefail

RUSTUP_INSTALLER_URL="https://sh.rustup.rs"

STATE_DIR="${RUST_SETUP_STATE_DIR:-${HOME}/.local/state/rust-setup}"
DOWNLOAD_DIR="${RUST_SETUP_DOWNLOAD_DIR:-${HOME}/.cache/rust-setup}"
RUN_ID="$(date +%Y%m%d-%H%M%S)"
LOG_FILE="${STATE_DIR}/install-${RUN_ID}.log"
ROLLBACK_FILE="${STATE_DIR}/rollback-${RUN_ID}.sh"

if [[ -t 1 ]]; then
  BOLD="$(printf '\033[1m')"
  DIM="$(printf '\033[2m')"
  RED="$(printf '\033[31m')"
  GREEN="$(printf '\033[32m')"
  YELLOW="$(printf '\033[33m')"
  BLUE="$(printf '\033[34m')"
  RESET="$(printf '\033[0m')"
else
  BOLD=""
  DIM=""
  RED=""
  GREEN=""
  YELLOW=""
  BLUE=""
  RESET=""
fi

APT_PACKAGES=(
  build-essential
  curl
  git
  libssl-dev
  binutils-arm-none-eabi
)

RUST_TARGETS=(
  thumbv6m-none-eabi
)

CARGO_TOOLS=(
  cargo-watch
  evcxr_repl
)

# Note: httpd://youtube.com in the original list was a typo; normalised to https://
CONNECTIVITY_SITES=(
  https://doc.rust-lang.org/book/
  https://doc.rust-lang.org/stable/rust-by-example/
  https://doc.rust-lang.org/cargo/
  https://doc.rust-lang.org/std/
  https://doc.rust-lang.org/stable/embedded-book/
  https://locka99.gitbooks.io/a-guide-to-porting-c-to-rust/content/
  https://www.rust-lang.org/learn/get-started
  https://code.visualstudio.com/docs/languages/rust
  https://youtube.com
  https://code.visualstudio.com/docs/editor/debugging?ref=hacf.fr
)

SELECTED_APT=()
SELECTED_RUST_TARGETS=()
SELECTED_CARGO_TOOLS=()
INSTALL_RUSTUP=0
INSTALL_RUST_SRC=0
INSTALL_VSCODE=0

INSTALLED_APT=()
INSTALLED_RUST_TARGETS=()
INSTALLED_CARGO_TOOLS=()
INSTALLED_OTHER=()
FAILED_ITEMS=()
SKIPPED_ITEMS=()

print_header() {
  printf '\n%s%s%s\n' "${BOLD}" "$1" "${RESET}"
  printf '%*s\n' "${#1}" '' | tr ' ' '-'
}

log() {
  mkdir -p "${STATE_DIR}" 2>/dev/null || true
  # shellcheck disable=SC2312
  printf '[%s] %s\n' "$(date --iso-8601=seconds)" "$*" >> "${LOG_FILE}"
}

prepare_runtime_dirs() {
  if ! mkdir -p "${STATE_DIR}" 2>/dev/null || ! ( : > "${STATE_DIR}/.write-test" ) 2>/dev/null; then
    printf '%s\n' "${YELLOW}Cannot write to ${STATE_DIR}; using a local log directory instead.${RESET}"
    STATE_DIR="${PWD}/rust-setup-logs"
    mkdir -p "${STATE_DIR}"
  else
    rm -f "${STATE_DIR}/.write-test"
  fi

  if ! mkdir -p "${DOWNLOAD_DIR}" 2>/dev/null || ! ( : > "${DOWNLOAD_DIR}/.write-test" ) 2>/dev/null; then
    printf '%s\n' "${YELLOW}Cannot write to ${DOWNLOAD_DIR}; using a local download cache instead.${RESET}"
    DOWNLOAD_DIR="${PWD}/rust-setup-downloads"
    mkdir -p "${DOWNLOAD_DIR}"
  else
    rm -f "${DOWNLOAD_DIR}/.write-test"
  fi

  LOG_FILE="${STATE_DIR}/install-${RUN_ID}.log"
  ROLLBACK_FILE="${STATE_DIR}/rollback-${RUN_ID}.sh"
}

init_rollback() {
  # shellcheck disable=SC2312
  printf '[%s] run started\n' "$(date --iso-8601=seconds)" > "${LOG_FILE}"

  {
    printf '#!/usr/bin/env bash\n'
    printf 'set -u\n'
    printf 'set -o pipefail\n\n'
    # shellcheck disable=SC2312
    printf '# Rollback commands generated by validate_embedded_rust_setup.sh on %s.\n' "$(date --iso-8601=seconds)"
    printf '# Only items installed directly by that run are listed here.\n\n'
  } > "${ROLLBACK_FILE}"
  chmod +x "${ROLLBACK_FILE}"
}

append_rollback() {
  printf '%s\n' "$*" >> "${ROLLBACK_FILE}"
}

status_label() {
  case "$1" in
    present) printf '%sinstalled%s' "${GREEN}" "${RESET}" ;;
    missing) printf '%smissing%s' "${RED}" "${RESET}" ;;
    selected) printf '%sselected%s' "${BLUE}" "${RESET}" ;;
    skipped) printf '%sskipped%s' "${YELLOW}" "${RESET}" ;;
    failed) printf '%sfailed%s' "${RED}" "${RESET}" ;;
    ok) printf '%sok%s' "${GREEN}" "${RESET}" ;;
    *) printf '%s' "$1" ;;
  esac
}

prompt_yes_no() {
  local prompt="$1"
  local default="${2:-n}"
  local answer suffix

  if [[ "${default}" == "y" ]]; then
    suffix="[Y/n]"
  else
    suffix="[y/N]"
  fi

  while true; do
    printf '%s %s ' "${prompt}" "${suffix}"
    if ! read -r answer; then
      printf '\nNo input available; defaulting to no.\n'
      return 1
    fi
    answer="${answer:-${default}}"
    case "${answer}" in
      y|Y|yes|YES|Yes) return 0 ;;
      n|N|no|NO|No) return 1 ;;
      *) printf 'Please answer yes or no.\n' ;;
    esac
  done
}

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

source_cargo_env() {
  if [[ -f "${HOME}/.cargo/env" ]]; then
    # shellcheck disable=SC1091
    . "${HOME}/.cargo/env"
  fi
}

apt_installed() {
  dpkg-query -W -f='${Status}' "$1" 2>/dev/null | grep -q 'install ok installed'
}

rust_target_installed() {
  command_exists rustup && rustup target list --installed 2>/dev/null | grep -Fxq "$1"
}

rust_component_installed() {
  command_exists rustup && rustup component list --installed 2>/dev/null | grep -Eq "^$1($|[ -])"
}

cargo_tool_installed() {
  case "$1" in
    cargo-watch) command_exists cargo-watch ;;
    evcxr_repl)  command_exists evcxr ;;
    *) return 1 ;;
  esac
}

cargo_tool_check_label() {
  case "$1" in
    cargo-watch) printf '%s' "cargo-watch --version" ;;
    evcxr_repl)  printf '%s' "evcxr --version" ;;
    *) printf '%s' "command/version" ;;
  esac
}

cargo_install_tool() {
  case "$1" in
    evcxr_repl) cargo install --locked "$1" ;;
    *)          cargo install "$1" ;;
  esac
}

vscode_installed() {
  command_exists code
}

normalize_url() {
  case "$1" in
    http://*|https://*) printf '%s' "$1" ;;
    *) printf 'https://%s' "$1" ;;
  esac
}

url_host() {
  local url="$1"
  url="${url#http://}"
  url="${url#https://}"
  url="${url%%/*}"
  url="${url%%:*}"
  printf '%s' "${url}"
}

url_port() {
  case "$1" in
    http://*) printf '%s' "80" ;;
    *) printf '%s' "443" ;;
  esac
}

test_tcp_reachable() {
  local url="$1"
  local host port

  host="$(url_host "${url}")"
  port="$(url_port "${url}")"

  if command_exists timeout; then
    timeout 5 bash -c ":</dev/tcp/${host}/${port}" >/dev/null 2>&1
  else
    bash -c ":</dev/tcp/${host}/${port}" >/dev/null 2>&1
  fi
}

test_site_reachable() {
  local input="$1"
  local url http_code

  url="$(normalize_url "${input}")"

  if command_exists curl; then
    http_code="$(
      curl -L -sS -o /dev/null -w '%{http_code}' \
        --connect-timeout 5 \
        --max-time 12 \
        --compressed \
        -A 'Mozilla/5.0 rust-readiness-check' \
        "${url}" 2>/dev/null || true
    )"
    if [[ "${http_code}" != "000" && -n "${http_code}" ]]; then
      return 0
    fi
  fi

  test_tcp_reachable "${url}"
}

print_connectivity_summary() {
  # shellcheck disable=SC2312
  local site url
  local reachable_count=0
  local failed_count=0

  print_header "Website reachability"
  printf '%-50s %-14s %s\n' "Site" "Result" "URL tested"
  printf '%-50s %-14s %s\n' "----" "------" "----------"

  for site in "${CONNECTIVITY_SITES[@]}"; do
    url="$(normalize_url "${site}")"
    if test_site_reachable "${site}"; then
      # shellcheck disable=SC2312
      printf '%-50s %-23b %s\n' "${site}" "$(status_label ok)" "${url}"
      reachable_count=$((reachable_count + 1))
      log "site reachable: ${url}"
    else
      # shellcheck disable=SC2312
      printf '%-50s %-23b %s\n' "${site}" "$(status_label failed)" "${url}"
      failed_count=$((failed_count + 1))
      log "site unreachable: ${url}"
    fi
  done

  printf '\nReachable: %s  Failed: %s\n' "${reachable_count}" "${failed_count}"
}

print_detection_table() {
  print_header "Readiness scan"
  printf '%-34s %-14s %s\n' "Item" "Status" "Verification"
  printf '%-34s %-14s %s\n' "----" "------" "------------"

  for package in "${APT_PACKAGES[@]}"; do
    if apt_installed "${package}"; then
      # shellcheck disable=SC2312
      printf '%-34s %-23b %s\n' "${package}" "$(status_label present)" "dpkg"
    else
      # shellcheck disable=SC2312
      printf '%-34s %-23b %s\n' "${package}" "$(status_label missing)" "apt package"
    fi
  done

  if command_exists rustup; then
    # shellcheck disable=SC2312
    printf '%-34s %-23b %s\n' "rustup" "$(status_label present)" "rustup --version"
  else
    # shellcheck disable=SC2312
    printf '%-34s %-23b %s\n' "rustup" "$(status_label missing)" "${RUSTUP_INSTALLER_URL}"
  fi

  for target in "${RUST_TARGETS[@]}"; do
    if rust_target_installed "${target}"; then
      # shellcheck disable=SC2312
      printf '%-34s %-23b %s\n' "rust target: ${target}" "$(status_label present)" "rustup target list"
    else
      # shellcheck disable=SC2312
      printf '%-34s %-23b %s\n' "rust target: ${target}" "$(status_label missing)" "rustup target add"
    fi
  done

  if rust_component_installed rust-src; then
    # shellcheck disable=SC2312
    printf '%-34s %-23b %s\n' "rust component: rust-src" "$(status_label present)" "rustup component list"
  else
    # shellcheck disable=SC2312
    printf '%-34s %-23b %s\n' "rust component: rust-src" "$(status_label missing)" "rustup component add"
  fi

  for tool in "${CARGO_TOOLS[@]}"; do
    if cargo_tool_installed "${tool}"; then
      # shellcheck disable=SC2312
      printf '%-34s %-23b %s\n' "cargo tool: ${tool}" "$(status_label present)" "$(cargo_tool_check_label "${tool}")"
    else
      # shellcheck disable=SC2312
      printf '%-34s %-23b %s\n' "cargo tool: ${tool}" "$(status_label missing)" "cargo install"
    fi
  done

  if vscode_installed; then
    # shellcheck disable=SC2312
    printf '%-34s %-23b %s\n' "Visual Studio Code" "$(status_label present)" "code --version"
  else
    # shellcheck disable=SC2312
    printf '%-34s %-23b %s\n' "Visual Studio Code" "$(status_label missing)" "snap install --classic code"
  fi
}

select_missing_items() {
  local package target tool

  print_header "Installation choices"
  printf '%s\n' "Answer yes for items you want this script to install now."

  for package in "${APT_PACKAGES[@]}"; do
    if ! apt_installed "${package}"; then
      if prompt_yes_no "Install apt package '${package}'?" "y"; then
        SELECTED_APT+=("${package}")
      else
        SKIPPED_ITEMS+=("${package}")
      fi
    fi
  done

  if ! command_exists rustup; then
    if prompt_yes_no "Install rustup using the official Rust installer?" "y"; then
      INSTALL_RUSTUP=1
    else
      SKIPPED_ITEMS+=("rustup")
    fi
  fi

  for target in "${RUST_TARGETS[@]}"; do
    if ! rust_target_installed "${target}"; then
      if prompt_yes_no "Install Rust target '${target}'?" "y"; then
        SELECTED_RUST_TARGETS+=("${target}")
      else
        SKIPPED_ITEMS+=("rust target: ${target}")
      fi
    fi
  done

  if ! rust_component_installed rust-src; then
    if prompt_yes_no "Install Rust component 'rust-src'?" "y"; then
      INSTALL_RUST_SRC=1
    else
      SKIPPED_ITEMS+=("rust component: rust-src")
    fi
  fi

  for tool in "${CARGO_TOOLS[@]}"; do
    if ! cargo_tool_installed "${tool}"; then
      if prompt_yes_no "Install Cargo tool '${tool}'?" "y"; then
        SELECTED_CARGO_TOOLS+=("${tool}")
      else
        SKIPPED_ITEMS+=("cargo tool: ${tool}")
      fi
    fi
  done

  if ! vscode_installed; then
    if prompt_yes_no "Install Visual Studio Code via snap?" "y"; then
      INSTALL_VSCODE=1
    else
      SKIPPED_ITEMS+=("Visual Studio Code")
    fi
  fi
}

ensure_sudo() {
  if [[ "${#SELECTED_APT[@]}" -gt 0 || "${INSTALL_VSCODE}" -eq 1 ]]; then
    sudo -v
  fi
}

install_apt_packages() {
  local package

  if [[ "${#SELECTED_APT[@]}" -eq 0 ]]; then
    return
  fi

  print_header "Installing apt packages"
  log "apt selected: ${SELECTED_APT[*]}"

  if sudo apt update && sudo apt install -y "${SELECTED_APT[@]}"; then
    for package in "${SELECTED_APT[@]}"; do
      if apt_installed "${package}"; then
        INSTALLED_APT+=("${package}")
        append_rollback "sudo apt purge -y '${package}'"
        log "apt installed: ${package}"
      else
        FAILED_ITEMS+=("${package}")
        log "apt install verification failed: ${package}"
      fi
    done
    append_rollback "sudo apt autoremove -y"
    return
  fi

  printf '%s\n' "${YELLOW}Batch apt install failed; retrying packages individually.${RESET}"
  log "apt batch failed; retrying individually"

  for package in "${SELECTED_APT[@]}"; do
    if apt_installed "${package}"; then
      continue
    fi

    if sudo apt install -y "${package}" && apt_installed "${package}"; then
      INSTALLED_APT+=("${package}")
      append_rollback "sudo apt purge -y '${package}'"
      log "apt installed after retry: ${package}"
    else
      FAILED_ITEMS+=("${package}")
      log "apt install failed: ${package}"
    fi
  done
  append_rollback "sudo apt autoremove -y"
}

install_rustup_if_needed() {
  if [[ "${INSTALL_RUSTUP}" -ne 1 ]]; then
    return
  fi

  print_header "Installing rustup"
  log "installing rustup"
  printf '%s\n' "${DIM}After installation, source \"\$HOME/.cargo/env\" or open a new shell.${RESET}"
  if curl --proto '=https' --tlsv1.2 -sSf "${RUSTUP_INSTALLER_URL}" | sh -s -- -y; then
    source_cargo_env
    if command_exists rustup; then
      INSTALLED_OTHER+=("rustup")
      append_rollback "rustup self uninstall -y"
      log "rustup installed"
    else
      FAILED_ITEMS+=("rustup")
      log "rustup installer completed but rustup was not found"
    fi
  else
    FAILED_ITEMS+=("rustup")
    log "rustup installer failed"
  fi
}

install_rust_items() {
  local target tool

  source_cargo_env

  if [[ "${#SELECTED_RUST_TARGETS[@]}" -gt 0 || "${INSTALL_RUST_SRC}" -eq 1 ]]; then
    if ! command_exists rustup; then
      printf '%s\n' "${RED}rustup is unavailable; skipping Rust targets/components.${RESET}"
      for target in "${SELECTED_RUST_TARGETS[@]}"; do
        FAILED_ITEMS+=("rust target: ${target}")
      done
      [[ "${INSTALL_RUST_SRC}" -eq 1 ]] && FAILED_ITEMS+=("rust component: rust-src")
    fi
  fi

  if command_exists rustup; then
    for target in "${SELECTED_RUST_TARGETS[@]}"; do
      print_header "Installing Rust target ${target}"
      if rustup target add "${target}" && rust_target_installed "${target}"; then
        INSTALLED_RUST_TARGETS+=("${target}")
        append_rollback "rustup target remove '${target}'"
        log "rust target installed: ${target}"
      else
        FAILED_ITEMS+=("rust target: ${target}")
        log "rust target install failed: ${target}"
      fi
    done

    if [[ "${INSTALL_RUST_SRC}" -eq 1 ]]; then
      print_header "Installing Rust component rust-src"
      if rustup component add rust-src && rust_component_installed rust-src; then
        INSTALLED_OTHER+=("rust component: rust-src")
        append_rollback "rustup component remove rust-src"
        log "rust component installed: rust-src"
      else
        FAILED_ITEMS+=("rust component: rust-src")
        log "rust component install failed: rust-src"
      fi
    fi
  fi

  if [[ "${#SELECTED_CARGO_TOOLS[@]}" -gt 0 ]]; then
    if ! command_exists cargo; then
      printf '%s\n' "${RED}cargo is unavailable; skipping Cargo tools.${RESET}"
      for tool in "${SELECTED_CARGO_TOOLS[@]}"; do
        FAILED_ITEMS+=("cargo tool: ${tool}")
      done
      return
    fi

    for tool in "${SELECTED_CARGO_TOOLS[@]}"; do
      print_header "Installing Cargo tool ${tool}"
      if cargo_install_tool "${tool}" && cargo_tool_installed "${tool}"; then
        INSTALLED_CARGO_TOOLS+=("${tool}")
        append_rollback "cargo uninstall '${tool}'"
        log "cargo tool installed: ${tool}"
      else
        FAILED_ITEMS+=("cargo tool: ${tool}")
        log "cargo tool install failed: ${tool}"
      fi
    done
  fi
}

install_vscode() {
  if [[ "${INSTALL_VSCODE}" -ne 1 ]]; then
    return
  fi

  print_header "Installing Visual Studio Code"
  log "installing VSCode via snap"

  if sudo snap install --classic code; then
    if vscode_installed; then
      INSTALLED_OTHER+=("Visual Studio Code")
      append_rollback "sudo snap remove code"
      log "VSCode installed"
    else
      FAILED_ITEMS+=("Visual Studio Code")
      log "VSCode snap install completed but code command not found"
    fi
  else
    FAILED_ITEMS+=("Visual Studio Code")
    log "VSCode snap install failed"
  fi
}

verify_final_state() {
  print_header "Final verification"
  printf '%-34s %-14s %s\n' "Item" "Result" "Check"
  printf '%-34s %-14s %s\n' "----" "------" "-----"

  verify_line "build-essential" "dpkg" apt_installed build-essential
  verify_line "curl" "curl --version" command_exists curl
  verify_line "git" "git --version" command_exists git
  verify_line "libssl-dev" "dpkg" apt_installed libssl-dev
  verify_line "binutils-arm-none-eabi" "dpkg" apt_installed binutils-arm-none-eabi
  verify_line "arm-none-eabi-objcopy" "command check" command_exists arm-none-eabi-objcopy
  verify_line "arm-none-eabi-objdump" "command check" command_exists arm-none-eabi-objdump
  verify_line "rustup" "rustup --version" command_exists rustup

  for target in "${RUST_TARGETS[@]}"; do
    verify_line "rust target: ${target}" "rustup target list" rust_target_installed "${target}"
  done

  verify_line "rust-src" "rustup component list" rust_component_installed rust-src
  verify_line "cargo-watch" "cargo-watch --version" cargo_tool_installed cargo-watch
  verify_line "evcxr_repl" "evcxr --version" cargo_tool_installed evcxr_repl
  verify_line "Visual Studio Code" "code --version" vscode_installed
}

verify_line() {
  local name="$1"
  local check="$2"
  local fn="$3"
  shift 3

  if "${fn}" "$@"; then
    # shellcheck disable=SC2312
    printf '%-34s %-23b %s\n' "${name}" "$(status_label ok)" "${check}"
  else
    # shellcheck disable=SC2312
    printf '%-34s %-23b %s\n' "${name}" "$(status_label failed)" "${check}"
  fi
}

run_std_rust_test() {
  local project_dir

  print_header "Rust std build and run test"

  if ! prompt_yes_no "Create, build, and run a simple std Rust program?" "n"; then
    log "Rust std test skipped by user"
    return
  fi

  source_cargo_env

  if ! command_exists cargo; then
    printf '%s\n' "${RED}cargo is not available; cannot build the test project.${RESET}"
    FAILED_ITEMS+=("Rust std test: cargo")
    log "Rust std test failed: cargo missing"
    return
  fi

  project_dir="${RUST_TEST_DIR:-${PWD}/rust-setup-tests}/hello_rust"
  mkdir -p "${project_dir}/src"

  printf '%s\n' "${DIM}Writing test project to ${project_dir}${RESET}"

  cat > "${project_dir}/Cargo.toml" <<'EOF'
[package]
name = "hello_rust"
version = "0.1.0"
edition = "2021"
EOF

  cat > "${project_dir}/src/main.rs" <<'EOF'
fn main() {
    println!("life moves too fast");
}
EOF

  print_header "Building hello_rust"
  if ! (cd "${project_dir}" && cargo build --release); then
    printf '%s\n' "${RED}cargo build --release failed for the test project.${RESET}"
    FAILED_ITEMS+=("Rust std test: cargo build")
    log "Rust std test failed: cargo build"
    return
  fi

  print_header "Running hello_rust"
  if (cd "${project_dir}" && cargo run --release); then
    INSTALLED_OTHER+=("Rust std build and run test")
    log "Rust std test completed"
  else
    FAILED_ITEMS+=("Rust std test: cargo run")
    log "Rust std test run failed"
  fi
}

print_run_summary() {
  local item

  print_header "Run summary"
  printf '%-34s %-14s\n' "Item" "Outcome"
  printf '%-34s %-14s\n' "----" "-------"

  for item in "${INSTALLED_APT[@]}"; do
    # shellcheck disable=SC2312
    printf '%-34s %-23b\n' "${item}" "$(status_label ok)"
  done
  for item in "${INSTALLED_RUST_TARGETS[@]}"; do
    # shellcheck disable=SC2312
    printf '%-34s %-23b\n' "rust target: ${item}" "$(status_label ok)"
  done
  for item in "${INSTALLED_CARGO_TOOLS[@]}"; do
    # shellcheck disable=SC2312
    printf '%-34s %-23b\n' "cargo tool: ${item}" "$(status_label ok)"
  done
  for item in "${INSTALLED_OTHER[@]}"; do
    # shellcheck disable=SC2312
    printf '%-34s %-23b\n' "${item}" "$(status_label ok)"
  done
  for item in "${SKIPPED_ITEMS[@]}"; do
    # shellcheck disable=SC2312
    printf '%-34s %-23b\n' "${item}" "$(status_label skipped)"
  done
  for item in "${FAILED_ITEMS[@]}"; do
    # shellcheck disable=SC2312
    printf '%-34s %-23b\n' "${item}" "$(status_label failed)"
  done

  printf '\nLog:      %s\n' "${LOG_FILE}"
  printf 'Rollback: %s\n' "${ROLLBACK_FILE}"
}

check_ubuntu() {
  if [[ ! -r /etc/os-release ]]; then
    printf '%s\n' "${RED}Cannot read /etc/os-release; this script supports Ubuntu only.${RESET}"
    exit 1
  fi

  # shellcheck disable=SC1091
  . /etc/os-release
  if [[ "${ID:-}" != "ubuntu" ]]; then
    printf '%s\n' "${RED}Unsupported OS '${ID:-unknown}'. This script supports Ubuntu only.${RESET}"
    exit 1
  fi
}

main() {
  check_ubuntu
  source_cargo_env
  prepare_runtime_dirs
  init_rollback

  printf '%s%sRust learning environment readiness check%s\n' "${BOLD}" "${BLUE}" "${RESET}"
  printf '%sUbuntu-only installer for Rust, VSCode, and related learning tools.%s\n' "${DIM}" "${RESET}"

  print_connectivity_summary
  print_detection_table
  select_missing_items
  ensure_sudo

  install_apt_packages
  install_rustup_if_needed
  install_rust_items
  install_vscode

  source_cargo_env
  verify_final_state
  run_std_rust_test
  print_run_summary
}

main "$@"
